#!/usr/bin/env perl
# basepods - print out the standard perl*.pod manpages pod paths

use Config;
$lib = "$Config{'installprivlib'}/pod";
opendir(LIB, $lib) || die "$0: can't opendir $lib: $!\n";
while ($_ = readdir(LIB)) { 
    print "$lib/$_\n" if /\.pod$/;
} 

__END__

=head1 NAME

basepods - print out pod paths for the standard perl manpages 

=head1 DESCRIPTION

This program uses your configuration's C<installprivlib> directory
to look up the full paths to those pod pages.  Any files in that
directory whose names end in C<.pod> will be printed to the standard
output, one per line.  This is normally used in backticks to produce
a list of filenames for other commands.

=head1 EXAMPLES

    $ podgrep typeglob `basepods`

    $ basepods | grep delt
    /usr/local/devperl/lib/5.00554/pod/perl5004delta.pod
    /usr/local/devperl/lib/5.00554/pod/perl5005delta.pod
    /usr/local/devperl/lib/5.00554/pod/perldelta.pod

You can also run this using alternate perl binaries, like so:

    $ oldperl -S basepods | grep delt
    /usr/lib/perl5/pod/perldelta.pod

    $ podgrep -i thread `filsperl basepods | grep delt`
    ....

=head1 SEE ALSO

faqpods(1), modpods(1), pods(1), sitepod(1), podpath(1), and stdpod(1).


=head1 AUTHOR and COPYRIGHT

Copyright (c) 1999 Tom Christiansen

This is free software.  You may modify it and distribute it 
under Perl's Artistic Licence.  Modified versions must be
clearly indicated.
