#!/usr/bin/env perl
# plxload -- show what files a perl program loads
# tchrist@perl.com

BEGIN { $^W = 1 }
BEGIN { die "usage: $0 filename\n" unless @ARGV == 1 }

$filename = shift;

use FindBin qw($Bin);

exec "$^X -I$Bin -MDevel::Loaded -S -c $filename 2>/dev/null";

__END__

=head1 NAME

plxload - show what files a perl program loads at compile time

=head1 SYNOPSYS

    $ plxload

=head1 DESCRIPTION

This program is used to show what modules a program would load at
compile time via C<use>.  Because this installs an at-exit handler and
then uses Perl's B<-c> flag for compile only, it will not find modules
loaded at run-time.  Use the Devel::Loaded module for that.

=head1 EXAMPLES

    $ plxload perldoc
    /usr/local/devperl/lib/5.00554/Exporter.pm
    /usr/local/devperl/lib/5.00554/strict.pm
    /usr/local/devperl/lib/5.00554/vars.pm
    /usr/local/devperl/lib/5.00554/i686-linux/Config.pm
    /usr/local/devperl/lib/5.00554/Getopt/Std.pm

    $ plxload /usr/src/perl5.005_54/installhtml
    /usr/local/devperl/lib/5.00554/Carp.pm
    /usr/local/devperl/lib/5.00554/Exporter.pm
    /usr/local/devperl/lib/5.00554/auto/Getopt/Long/autosplit.ix
    /usr/local/devperl/lib/5.00554/strict.pm
    /usr/local/devperl/lib/5.00554/vars.pm
    /usr/local/devperl/lib/5.00554/Pod/Functions.pm
    /usr/local/devperl/lib/5.00554/Getopt/Long.pm
    /usr/local/devperl/lib/5.00554/i686-linux/Config.pm
    /usr/local/devperl/lib/5.00554/lib.pm
    /home/tchrist/perllib/Pod/Html.pm
    /usr/local/devperl/lib/5.00554/Cwd.pm
    /usr/local/devperl/lib/5.00554/AutoLoader.pm

=head1 SEE ALSO

L<Devel::Loaded> and pmload(1).

=head1 AUTHOR and COPYRIGHT

Copyright (c) 1999 Tom Christiansen

This is free software.  You may modify it and distribute it 
under Perl's Artistic Licence.  Modified versions must be
clearly indicated.
