#!/usr/bin/env perl
# pmls -- show date stamp of module
# tchrist@perl.com

BEGIN { $^W = 1 }

use FindBin qw($Bin);

unless (@ARGV) {
    die "usage: $0 module ...\n";
} 
for $module (@ARGV) { 
    system "ls -l " . `$^X -S $Bin/pmpath $module`;
}

__END__

=head1 NAME

pmls - long list the module path

=head1 DESCRIPTION

This is mostly here for people too lazy to type

    $ ls -l `pmpath CGI` 

=head1 EXAMPLES

    $ pmls CGI
    -r--r--r--   1 root     root       190901 Dec  6 03:19
		/usr/local/devperl/lib/5.00554/CGI.pm


    $ oldperl -S pmls CGI
    -r--r--r--   1 root     root       186637 Sep 10 00:18 
		/usr/lib/perl5/CGI.pm

=head1 SEE ALSO

pmpath(1)

=head1 AUTHOR and COPYRIGHT

Copyright (c) 1999 Tom Christiansen

This is free software.  You may modify it and distribute it 
under Perl's Artistic Licence.  Modified versions must be
clearly indicated.
