#!/usr/bin/env perl
# sitepods - print out the paths to the modules
#           that this site added
# 
# this is a perl program not a shell script
# so that we can use the correct perl 

open(PROG, "$^X -S modpods |") || die "can't fork: $!";

while (<PROG>) {
    print if /site_perl/;
} 

__END__

=head1 NAME

sitepods - print out the paths to the modules that this site added

=head1 DESCRIPTION

This program shows the paths to module pods that are in 
the I<site_perl> directories.

=head1 EXAMPLES

    $ sitepods
    /usr/local/devperl/lib/site_perl/5.00554/i686-linux/XML/Parser/Expat.pm
    /usr/local/devperl/lib/site_perl/5.00554/i686-linux/XML/Parser.pm

You can also run this using alternate perl binaries, like so:

    $ oldperl -S sitepods  
    ....

=head1 SEE ALSO

faqpods(1), modpods(1), pods(1), podpath(1), and stdpod(1).


=head1 AUTHOR and COPYRIGHT

Copyright (c) 1999 Tom Christiansen

This is free software.  You may modify it and distribute it 
under Perl's Artistic Licence.  Modified versions must be
clearly indicated.
